config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'static_pages/home'
  match "/info_email" => "discs/info_email", :controller => 'discs', :action => 'info_email', via: [:get, :post]

  resources :discs do
    member do
      get 'buy'
      post 'buy'
      get 'info_email'
      post 'info_email'
    end
  end

  root to: 'static_pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :disc

	validates :email_source, :disc_id, presence: true
	validates :description, presence: true, length: { minimum: 10 }  
end

app/models/disc.rb
class Disc < ActiveRecord::Base
	validates :name, :year, :price, :state, presence: true
	validates :description, presence: true, length: { minimum: 10 }
  has_attached_file :avatar, styles: { large: "400x300", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment :avatar, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

  #has_many :comments, class_name: "Comment", foreign_key: "comment_id", :as => :comment, dependent: :destroy
  has_many :comments
  
  geocoded_by :address 
  after_validation :geocode, :if => :address_changed?

	def state_name
    case self.state
      when 0  then "Selado"
      when 1  then "Quase Perfeito"
      when 2  then "Excelente"
      when 3  then "Muito Bom"
      when 4  then "Bom"
      when 5  then "Regular"
      when 6  then "Ruim"
    else "Nao Definido"
    end
	end

  def feed
    Comment.where("disc_id = ?", self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
#  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def create
    @disc = Disc.find(params[:comment][:disc_id])
    @comment = Comment.new(comment_params)

    if @comment.save
      #@comment.send_notification_email
      flash[:success] = "Comment created!"
      redirect_to disc_path(@disc)
    else
      flash[:danger] = "Error Comment!"
      redirect_to disc_path(@disc)
    end    
  end

  private
    # Never trust parameters dzsc_pathfrom the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:email_source, :disc_id, :description)
    end
end

app/controllers/discs_controller.rb
class DiscsController < ApplicationController
  #http_basic_authenticate_with name: "loja", password: "vinil", except: [:show, :index, :buy] 
  before_action :set_disc, only: [:show, :edit, :update, :destroy, :buy, :info_email]

  # GET /discs
  # GET /discs.json
  def index
    @discs = Disc.all
  end

  # GET /discs/1
  # GET /discs/1.json
  def show
    @comment = @disc.comments.build
    @hash = Gmaps4rails.build_markers(@disc) do |disc, marker|
      marker.lat disc.latitude
      marker.lng disc.longitude
    end  
  end

  # GET /discs/new
  def new
    @disc = Disc.new
  end

  # GET /discs/1/edit
  def edit
  end

  # POST /discs
  # POST /discs.json
  def create
    @disc = Disc.new(disc_params)

    respond_to do |format|
      if @disc.save
        format.html { redirect_to @disc, notice: 'Disc was successfully created.' }
        format.json { render :show, status: :created, location: @disc }
      else
        format.html { render :new }
        format.json { render json: @disc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discs/1
  # PATCH/PUT /discs/1.json
  def update
    respond_to do |format|
      if @disc.update(disc_params)
        format.html { redirect_to @disc, notice: 'Disc was successfully updated.' }
        format.json { render :show, status: :ok, location: @disc }
      else
        format.html { render :edit }
        format.json { render json: @disc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discs/1
  # DELETE /discs/1.json
  def destroy
    @disc.destroy
    respond_to do |format|
      format.html { redirect_to discs_url, notice: 'Disc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def buy
    respond_to do |format|
      DiscMailer.buy_email(@disc, params[:informar][:email]).deliver_now
      format.html { redirect_to @disc, notice: 'Disc successfully purchased.' }
    end
  end

  def info_email
    respond_to do |format|
      format.html
      format.js
    end    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disc
      @disc = Disc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disc_params
      params.require(:disc).permit(:name, :year, :price, :state, :avatar, :description, :address, :latidude, :longitude)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
    base_title = "Vinyl Store"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end	

  def select_state
    ([["Selado", 0], ["Quase Perfeito", 1], ["Excelente", 2], ["Muito Bom", 3], ["Bom", 4], ["Regular", 5], ["Ruim", 6]])
  end

  def range_year
    #(1950..Date.today.year).to_a, Date.today.year)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_comment.html.erb
<li>
  <p>
  	De: <%= comment.email_origem %> | Para: <%= comment.email_destino %>	
  </p>
	<p>
		<%= comment.content %>
	</p>
</li>

app/views/comments/_feed.html.erb
<div class="panel-group accordion" id="accordion1" role="tablist" aria-multiselectable="true">
  <% comments.each do |comment| %>  
  <div class="panel panel-default accordion-group">
    <div class="panel-heading accordion-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapse_comment_<%= comment.id %>">
          De: <%= comment.email_source %>
          <small style="color:#999"><%= comment.created_at %></small>
        </a>
      </h4>
    </div>
    <div id="collapse_comment_<%= comment.id %>" class="accordion-body collapse">
      <div class="accordion-inner">
        <div class=" panel-group accordion" id="accordion2" role="tablist" aria-multiselectable="true">
          <ul>
            <p>
              <pre><%= comment.description %></pre> 
            </p>
          </ul>
          
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/comments/_fields.html.erb
<div class="form-group">
  <%= f.text_field :email_source, class: "form-control", placeholder: "Informe o(s) email(s) de destino..." %>
</div>
<div class="form-group">
  <%= f.text_area :description, rows: 5, class: "form-control", placeholder: "Escreva o comentário..." %>
</div>

app/views/comments/_form_comment.html.erb
<%= form_for(@comment, html: {multipart: true	}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
 
  <%= hidden_field_tag "comment[disc_id]", @disc.id %>

  <%= render 'comments/fields', f: f %>
  
  <%= f.submit "Enviar comentario", class: "btn btn-success" %>
<% end %>

app/views/discs/_form.html.erb
<%= form_for @disc, html: { multipart: true } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :year %><br>
    <%= f.select :year, options_for_select( (1950..Date.today.year).to_a, Date.today.year), {include_blank: true}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %><br>
    <%= f.select( :state, select_state, {include_blank: "Select State"}, {class: "form-control"} ) %>      
  </div>

  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :latidude %><br>
    <%= f.text_field :latitude, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.file_field :avatar, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", rows: 6 %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "View",  disc_path(@disc), class: "btn btn-info" if !@disc.new_record? %>
    <%= link_to "List All", discs_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/discs/_info_email.html.erb
<div class="modal fade bs-example-modal-sm" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Informe um email</h4>
      </div>
      <div class="modal-body">
        <%= form_tag({:controller => "discs", action: :buy}, :method => "post", :name => "buy") do |f| %>
          <div class="form-group">
            <%= label_tag :email, "Email" %><br>
            <%= text_field_tag "informar[email]", nil, class: "form-control" %>
          </div>
      </div>
      <div class="modal-footer">
        <%= submit_tag("Buy Now", class: "btn btn-primary") %> 
      </div>
     <% end %>
    </div>
  </div>
</div>

app/views/discs/edit.html.erb
<h1>Editing Disc</h1>

<%= render 'form' %>

app/views/discs/index.html.erb
<p id="notice"><%#= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">Listing Discs</div>
  <div class="panel-body">
    <%= link_to 'New Disc', new_disc_path, class: "btn btn-primary btn-lg btn-block" %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Year</th>
            <th>Price</th>
            <th>State</th>
            <th colspan="3">Options</th>
         </tr>
        </thead>

        <tbody>
          <% @discs.each do |disc| %>
            <tr>
              <td><%= disc.name %></td>
              <td><%= disc.year %></td>
              <td><%= disc.price %></td>
              <td><%= disc.state_name %></td>
              <td><%= link_to 'Show', disc, class: "btn btn-info btn-sm" %></td>
              <td><%= link_to 'Edit', edit_disc_path(disc), class: "btn btn-primary btn-sm"  %></td>
              <td><%= link_to 'Destroy', disc, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>    
  </div>
</div>

app/views/discs/new.html.erb
<h1>New Disc</h1>

<%= render 'form' %>

app/views/discs/show.html.erb
<p>
  <%= image_tag @disc.avatar.url(:thumb) %>  
</p>

<p>
  <strong>Name:</strong>
  <%= @disc.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @disc.year %>
</p>

<p>
  <strong>Price:</strong>
  <%= @disc.price %>
</p>

<p>
  <strong>State:</strong>
  <%= @disc.state_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @disc.description %>
</p>


<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">


  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingNine">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseNine" aria-expanded="false" aria-controls="collapseNine">
          Comentarios
        </a>
      </h4>
    </div>
    <div id="collapseNine" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingNine">
      <div class="panel-body">

      <%= render 'comments/feed', comments: @disc.feed %>

      <%= render 'comments/form_comment' %>
      
      </div>
    </div>
  </div>
</div>


<div class="form-group">
  <%= link_to 'Edit', edit_disc_path(@disc), class: "btn btn-primary" %>
  <%= link_to 'List All', discs_path, class: "btn btn-default" %>
  <%= link_to 'Buy', info_email_path,  {:remote => true, 'data-toggle' => "modal", 'data-target' => '.bs-example-modal-sm', class: "btn btn-success"}  %>  
</div>

<%= render partial: "info_email" %>

<script type="text/javascript">
$(function(){

  handler = Gmaps.build('Google');
  handler.buildMap({ internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });

})
</script>

<p>
  <div style='width: 450px;'>
  <div id="map" style='width: 400px; height: 200px;'></div>
  </div>
  
</p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand"><%= full_title(yield(:title)) %></a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "New Disc", new_disc_path %></li>
        <li><%= link_to "All Disc", discs_path %></li>

        </ul>        
    </div><!-- /.navbar-collapse -->
    
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">

    <script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
						  <div class="container">
						    <% flash.each do |key, value| %>
						      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
						    <% end %>
						    
	              <%= yield %>
  
  					    <%= debug(params) if Rails.env.development? %>
  
  					  </div>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t 'errors.template.count_errors' %> <%= pluralize(object.errors.count, "error"  ) %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
      <table class="table table-striped">
        <thead>
          <tr>
          <th></th>
         </tr>
        </thead>

        <tbody>
          <% Disc.all.each do |disc| %>
            <tr>
              <td><%= link_to image_tag(disc.avatar.url(:thumb)), disc %></td>


            </tr>
          <% end %>
        </tbody>
      </table>